apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollout-demo
  name: rollout-demo
  namespace: my-app
  annotations:
    a8r.io/description: Demo service to try the rollout feature
    a8r.io/owner: Ambassador Labs
    a8r.io/documentation: https://www.getambassador.io/docs/cloud/latest/service-catalog/howtos/rollout/
    a8r.io/repository: git@github.com:team-ship/rollouts-demo.git
    a8r.io/support: https://a8r.io/Slack
    a8r.io/rollouts.scm.path: manifests/rollout-demo
    a8r.io/rollouts.scm.branch: main
    a8r.io/rollouts.image-repo.type: dockerhub
    a8r.io/rollouts.image-repo.name: hashicorp/http-echo
    a8r.io/rollouts.deployment: rollout-demo
    a8r.io/rollouts.mappings: rollout-demo-mapping
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollout-demo
